// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcgen

import (
	"database/sql"
)

type Signal struct {
	Name   string
	Wid    string
	Src    string
	Filter sql.NullString
	Active bool
}

type Workflow struct {
	Wid   string
	Tname string
}
